# Generated by Django 3.2.7 on 2021-11-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_jots_jot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jot',
            old_name='task',
            new_name='title',
        ),
    ]
