# Generated by Django 3.2.7 on 2021-11-23 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_subjot'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjot',
            name='jot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.jot'),
            preserve_default=False,
        ),
    ]
