# Generated by Django 3.2.7 on 2021-11-25 02:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0006_auto_20211123_2252'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Jot',
        ),
        migrations.RenameModel(
            old_name='SubTask',
            new_name='SubJot',
        ),
        migrations.RenameField(
            model_name='subjot',
            old_name='task',
            new_name='jot',
        ),
    ]
